apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooks-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooks
  template:
    metadata:
      labels:
        app: hooks
    spec:
      containers:
      - name: hooks-example
        image: postgres:13
        command: ["/bin/sh","-c"]
        args:
          - postgres
          - -c
          - archive_mode=off
          - -c
          - archive_command=/usr/bin/wal-g wal-push %p
          - -c
          - wal_level=replica
          - -c
          - archive_timeout=1200
          - -c
          - max_wal_senders=2
          - -c
          - restore_command=/usr/bin/wal-g wal-fetch "%f" "%p" >> /tmp/wal.log 2>&1
        env:
          - name: POSTGRES_PASSWORD
            value: example-password
