apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooks-example-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooks
  template:
    metadata:
      labels:
        app: hooks
    spec:
      containers:
      - image: postgres:13
        name: hooks-example
