apiVersion: skaffold/v2beta21
kind: Config
build:
  artifacts:
  - image: ticket/postgres
    context: components/db
  - image: social-tag/social-tag-migrate
    context: components/migrate
  local:
    push: true
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - db-deployment.yaml
      # - migrate-deployment.yaml
