apiVersion: v1
kind: Service
metadata:
  name: leeroy-app
  labels:
    app: leeroy-app
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: leeroy-app
  selector:
    app: leeroy-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leeroy-app
  labels:
    app: leeroy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leeroy-app
  template:
    metadata:
      labels:
        app: leeroy-app
    spec:
      containers:
      - name: leeroy-app
        image: xcindall/leeroy-app:v1.29.0-56-ge310b9dab-dirty@sha256:52420d8706246a4847f862ddd499328c12a21398e6e63b682d3bde4aaabdec11
        ports:
        - containerPort: 50051
          name: http
